package server

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"time"

	"github.com/harsha-moparthy/llmgw/internal/apiv1"
	"github.com/harsha-moparthy/llmgw/internal/budget"
	"github.com/harsha-moparthy/llmgw/internal/cache"
	"github.com/harsha-moparthy/llmgw/internal/metrics"
	"github.com/harsha-moparthy/llmgw/internal/money"
	"github.com/harsha-moparthy/llmgw/internal/provider"
	"github.com/harsha-moparthy/llmgw/internal/router"
	"github.com/harsha-moparthy/llmgw/internal/sse"
)

// providerResult aliases the router/provider result type so the non-streaming
// helper signatures read cleanly.
type providerResult = provider.Result

// jsonEncode writes v as JSON to w.
func jsonEncode(w io.Writer, v any) error { return json.NewEncoder(w).Encode(v) }

// sseWriter implements router.StreamSink over an http.ResponseWriter.
//
// It is the concrete realisation of the transparent-failover window: it does NOT
// write the response headers or any frame until the first CONTENT chunk arrives.
// Until then Contentful() is false and the router may retry another provider.
// Once the first content is written, the headers are committed and a subsequent
// failure can only be surfaced, not retried — which is exactly the honesty
// boundary the router documents.
type sseWriter struct {
	w        http.ResponseWriter
	enc      *sse.Encoder
	req      *apiv1.ChatRequest
	logger   loggerT
	headerFn func() // called once, just before the first frame, to stamp headers

	started    bool
	contentful bool
	frames     int
	firstAt    time.Time
	// clientGone is set if a write to the client failed; the router treats the
	// returned error as a client disconnect.
	clientGone bool
}

func (s *sseWriter) ensureStarted() error {
	if s.started {
		return nil
	}
	// Stamp the gateway headers and the SSE headers, then commit the status.
	// This is the point of no return for failover: after WriteHeader the client
	// has a 200 and a content-type, so we can no longer switch providers
	// transparently.
	if s.headerFn != nil {
		s.headerFn()
	}
	sse.WriteHeaders(s.w.Header())
	enc, err := sse.NewEncoder(s.w)
	if err != nil {
		return err
	}
	s.w.WriteHeader(http.StatusOK)
	s.enc = enc
	s.started = true
	return nil
}

// OnChunk forwards a content chunk, starting the response on the first one.
func (s *sseWriter) OnChunk(chunk *apiv1.ChatChunk, raw []byte) error {
	// Only content chunks open the response and count as "contentful". An
	// opening role frame with empty content does NOT close the failover window,
	// because a provider that emits its role frame and then immediately dies is
	// still cleanly replaceable.
	hasContent := chunk != nil && chunk.DeltaText() != ""

	if !s.started {
		if !hasContent {
			// Buffer nothing, write nothing: keep the window open. The role frame
			// will be regenerated by whichever provider ultimately serves.
			return nil
		}
		if err := s.ensureStarted(); err != nil {
			return err
		}
		// Emit a synthetic role-opening frame first so the client sees a
		// well-formed OpenAI stream, then the content.
		role := &apiv1.ChatChunk{
			ID: chunk.ID, Object: apiv1.ObjectChatCompletionChunk, Created: chunk.Created, Model: chunk.Model,
			Choices: []apiv1.Choice{{Index: 0, Delta: &apiv1.Message{Role: apiv1.RoleAssistant, Content: apiv1.NewTextContent("")}}},
		}
		if b, err := json.Marshal(role); err == nil {
			_ = s.enc.WriteData(b)
		}
		s.firstAt = time.Now()
	}

	// Prefer the provider's raw bytes for passthrough fidelity, but for the
	// synthesised opening we already wrote, and for anthropic-normalised chunks,
	// marshal our chunk. Raw is used when present and parseable.
	var payload []byte
	if len(raw) > 0 && raw[0] == '{' {
		payload = raw
	} else if chunk != nil {
		if b, err := json.Marshal(chunk); err == nil {
			payload = b
		}
	}
	if payload == nil {
		return nil
	}
	if err := s.enc.WriteData(payload); err != nil {
		s.clientGone = true
		return err
	}
	if hasContent {
		s.contentful = true
	}
	s.frames++
	return nil
}

func (s *sseWriter) Contentful() bool { return s.contentful }

// OnError surfaces a mid-stream failure. If the stream had already started, the
// client gets an explicit error frame (not a silent EOF that reads as a normal
// end); if it never started, the caller writes a normal HTTP error instead.
func (s *sseWriter) OnError(f *provider.Failure) {
	if !s.started {
		// Nothing was written yet; the handler will send an HTTP error.
		return
	}
	env := apiv1.NewError(apiv1.ErrTypeUpstream, f.Class.String(),
		"upstream failed after streaming began: "+f.Error())
	if b, err := json.Marshal(env); err == nil {
		// A named error event so a client can distinguish it from a data frame.
		_ = s.enc.WriteEvent("error", b)
	}
	// Deliberately DO emit [DONE] after the error frame so a lenient client's
	// stream terminates cleanly; strict clients key on the error event.
	_ = s.enc.WriteDone()
}

// OnDone terminates a clean stream.
func (s *sseWriter) OnDone() {
	if !s.started {
		// A stream that produced no content at all: start it so the client gets a
		// valid (empty) stream rather than a hanging connection.
		if err := s.ensureStarted(); err != nil {
			return
		}
	}
	if s.req.WantsUsage() {
		// Usage was forwarded inline as its own frame by the provider stream, so
		// nothing extra to do here beyond the sentinel.
	}
	_ = s.enc.WriteDone()
}

// serveStreaming runs the streaming path.
func (s *Server) serveStreaming(w http.ResponseWriter, r *http.Request, tenant tenantT, route *router.Route, req *apiv1.ChatRequest, reqID string, reservation budget.Reservation, committed *bool, collector *attemptCollector, execOpt router.ExecOptions, scope cache.Scope, start time.Time) {
	ctx := provider.WithCorrelation(r.Context(), provider.Correlation{RequestID: reqID, Attempt: 1})

	sink := &sseWriter{
		w:      w,
		req:    req,
		logger: s.deps.Logger,
		headerFn: func() {
			w.Header().Set(HeaderRequestID, reqID)
			w.Header().Set(HeaderCache, "miss")
		},
	}

	ar, fail := s.deps.Router.ExecuteStream(ctx, tenant.ID, route, req, sink, execOpt)

	upstreamUs := s.flushLedger(collector, reqID, req.Model, tokenEstimate{prompt: execOpt.EstPromptTokens, max: execOpt.EstMaxTokens}, start)

	// Resolve the budget with the actual streamed cost.
	actualCost := s.streamedCost(collector, ar)
	if s.deps.Budget != nil && reservation.Valid() {
		_, _ = s.deps.Budget.Commit(reservation, actualCost)
		*committed = true
	}

	if fail != nil && !sink.started {
		// The whole chain failed before any content — a clean HTTP error, since
		// nothing was written to the client yet.
		status := statusForFailure(fail)
		s.recordRequestMetric(tenant.ID, req.Model, status, start)
		writeError(w, status, apiv1.ErrTypeUpstream, fail.Class.String(), fail.Error())
		return
	}

	// A stream ran (cleanly or surfaced an error mid-stream). Update the prior and
	// metrics from whatever was served.
	if ar.ServedModel != "" {
		s.updatePriorFromCollector(tenant.ID, ar.ServedModel, collector)
	}
	if sink.started {
		s.recordStreamMetrics(tenant.ID, req.Model, sink, ar, start)
	}
	// Note: cache population is skipped on the streaming path. The gateway does
	// not reassemble a streamed response into a cacheable body here — a streamed
	// answer is cached via its non-streaming twin (same cache key, since the
	// stream flag is excluded from the key), so a later non-streaming request
	// populates the cache and a later streaming request replays it. Documented
	// rather than silently doing nothing.
	_ = upstreamUs
}

// streamedCost sums the cost of the served attempt from the collected outcomes.
func (s *Server) streamedCost(collector *attemptCollector, ar *router.AttemptResult) money.Pico {
	collector.mu.Lock()
	defer collector.mu.Unlock()
	for _, o := range collector.outcomes {
		if o.Failure == nil || o.Served {
			return o.Cost
		}
	}
	return 0
}

func (s *Server) updatePriorFromCollector(tenant, model string, collector *attemptCollector) {
	collector.mu.Lock()
	defer collector.mu.Unlock()
	for _, o := range collector.outcomes {
		if o.Usage != nil && (o.Failure == nil || o.Served) {
			s.updatePrior(tenant, model, o.Usage)
			return
		}
	}
}

func (s *Server) recordStreamMetrics(tenant, model string, sink *sseWriter, ar *router.AttemptResult, start time.Time) {
	if s.deps.Metrics == nil {
		return
	}
	m := s.deps.Metrics
	s.recordRequestMetric(tenant, model, http.StatusOK, start)
	if !sink.firstAt.IsZero() {
		metrics.ObserveSeconds(m.StreamTTFB.With(metrics.Labels{"model": model}), sink.firstAt.Sub(start))
	}
	m.StreamFrames.With(metrics.Labels{"model": model}).Add(float64(sink.frames))
	if sink.clientGone {
		m.StreamAbandoned.With(metrics.Labels{"reason": "client_gone"}).Inc()
	}
	m.Attempts.With(metrics.Labels{"model": model}).Observe(float64(ar.Attempts))
}

// streamCachedEntry serves a cached response as a synthetic SSE stream.
func (s *Server) streamCachedEntry(w http.ResponseWriter, req *apiv1.ChatRequest, entry *cache.Entry) error {
	enc, err := sse.NewEncoder(w)
	if err != nil {
		return err
	}
	sse.WriteHeaders(w.Header())
	w.WriteHeader(http.StatusOK)
	chunks := entry.Replay(24, req.WantsUsage())
	for _, c := range chunks {
		b, err := json.Marshal(c)
		if err != nil {
			continue
		}
		if err := enc.WriteData(b); err != nil {
			return err
		}
	}
	return enc.WriteDone()
}

// loggerT is the minimal logger interface the sink needs.
type loggerT interface {
	Warn(msg string, args ...any)
	Error(msg string, args ...any)
}

var _ context.Context // context imported for signature symmetry with the router
